Clever/dev-handbook

git-workflow.md
Previously the git workflow did not talk about how the PRs should be assigned back to the reviewer once the the comments are addressed (which is what we usually do).
=> Add info about assigning PRs while addressing comments during review

git-workflow.md
Apparently we have enabled JIRA integration with Github. So commit messages containing a ticket ID are automatically listed under the "development" tab in JIRA, for example here:
https://clever.atlassian.net/browse/SCHOOLS-631
This adds instructions to include the ticket identifier in the commit message.
=> Added instructions to put the JIRA ticket identifier in the commit message

golang/README.md, style.md
I feel like having all go resources bundled together make more sense than having some of it under Style. Especially since we have a whole subfolder dedicated to go.
What do you think? another option is to create a new style.md under the golang folder.
=> [Proposal] Move golang style to golang README

security/bug-bounty.md
This is the bug bounty policy from our [HackerOne page](https://hackerone.com/clever?view_policy=true).
I'd like to host this on Github for a few reasons:
1) It's easier to track changes.
2) It's in markdown format, so preserving format is easier than in Confluence or Google docs.
3) We may get some interesting external pull requests.
This will be followed up by a few PRs updating the policy. Stay tuned!
=> Add bug bounty policy

security/bug-bounty.md
This change updates the language for the bug bounty policy and includes details about the scope of the bounty, including how to sign up for accounts.
=> Update bug bounty policy with information about how to sign up for accounts

make/README.md, make/thrift.mk
Issue: thrift projects typically contain version number in package.json as well as VERSION file. Bumping the version is often missed as the operation is not streamlined.
Solution: Add an additional helper in the thrift.mk file that add a command `make thrift-bump-patch`. Where patch can be minor/major/patch. The command increments the relevant version in both package.json and VERSION files.
=> Add bump helper to thrift.mk

make/README.md, make/node.mk
**Context**
We currently do a version check in the server file which is a little brittle and harder to scale across repos. Also it doesn't perform the check for other targets (notably tests) which then might fail with error messages that are not descriptive.
**Changes**
This PR adds a `node.mk` makefile with a function that checks the node version. Borrows from the [golang version check](https://github.com/Clever/dev-handbook/blob/bad3fcd493060c1a878c1ae2af7e3e452eb1b78f/make/golang.mk#L10-L16) and the one in [schools dashboard](https://github.com/Clever/schools-dashboard/blob/7f4984fd40624a958409b5ef3a9f8b00641692ad/Makefile#L64-L68)
Also adds example usage to the README.
**Tested**
Verified that the example makefile correctly does version checks for the `run` target.
=> Add a node.mk makefile with a version check function

make/node.mk
The previous function did not work because it mixed up bash functions (the conditional) and makefile functions (error). This PR changes the implementation to use pure makefile functions, similar to the golang makefile.
Tested:
Verified that adding
```makefile
NODE_VERSION := "v6"
$(eval $(call node-version-check,$(NODE_VERSION)))
```
causes the test to return an error when versions 0 or 5 are used, but pass when version 6 is used.
=> Fixes node version check to only use makefile functions

make/README.md, make/node.mk
**Context**
Coffee script has been deprecated and all new files should be written in ES6.
**Changes**
This PR adds a function that checks the count of coffee script files in a repo and exits if it doesn't match the expectations
**Tested**
Copied the function to schools-dashboard makefile and verified that three cases function as intended.
=> Add a function to check the count of coffeescript files to node.mk

make/node.mk
`$TMPDIR` is set on OS X but not in the VM (Ubuntu), apparently which caused errors like
```
Checking count of coffeescript files
/bin/bash: /node-coffee-file-count: Permission denied
make: *** [coffee-filecount-check] Error 1
```
Replaces `$TMPDIR` with `/tmp` going with the infra philosophy of only supporting the vm setup.
Tested by copying it to another repo and making sure the function still works
=> Change coffee file count function to use /tmp instead of $TMPDIR

make/swagger.mk
The generated Go code contains `go generate` directives that depend on mockgen. Encode this dependency.
=> swagger.mk: add dependency on mockgen for go codegen

make/swagger.mk
Previously, this file assumed the user's primary group was the same name
as the user itself. This change instead looks up the primary group for
the user explicitly.
For me, this change was necessary to run `make generate` when using
DockerForMac (my username is `nathanleiby` and group is `staff`).
=> swagger.mk - get user's group

make/golang.mk, make/node.mk, make/swagger.mk, make/thrift.mk
Running a command like
```bash
make swagger-update-makefile
``` 
now overwrites your local `swagger.mk` with the latest version from the dev-handbook.
also supported
```bash
make thrift-update-makefile
make golang-update-makefile
make node-update-makefile
```
=> make: add self-update functionality

make/wag.mk
This updates the wag Makefile
- Explicitly require users to set `WAG_VESION := X.X.X` in their makefiles. 
- Allow (and encourage) users to set `WAG_VERSION := latest`
- Only downloads new wag if the local version doesn't match specified version. 
- Puts wag in `./bin`
- Adds better logging and also quiets unnecessary curl logging etc.
=> Updated wag Makefile

make/wag.mk
`WAG_INSTALLED` needs bash to use `[[`. We didn't catch this before because `WAG_INSTALLED` had a lazy set (`=` instead of `:=`), so at the time of evaluation, shell had been set.
=> wag.mk: Move shell declaration up.

make/golang.mk
This allows us to commit `gomock` generated files which are not golint compliant.
I would prefer choosing a single prefix to omit that can be closely aligned w/ the `go:generate` directive.
I think `gen_` is concise enough to convey that it is a generated file but am open to other prefixes to "bless".
=> ignore gen_*.go files for golint

make/golang.mk
In CircleCI, the default GOPATH has multiple dirs:
GOPATH=dir1;dir2;...
We only want to use the first one of these.
The rest of `golang.mk` already expects a $(GOPATH) with only one
directory in it.
=> make/golang.mk - use only first dir in GOPATH

make/wag.mk
Without this binary on my system, I get the following error:
```
go generate github.com/Clever/app-service/gen-go/server github.com/Clever/app-service/gen-go/client github.com/Clever/app-service/gen-go/models
gen-go/server/interface.go:9: running "/Users/abhinavgarg/go/bin/mockgen": fork/exec /Users/abhinavgarg/go/bin/mockgen: no such file or directory
gen-go/client/interface.go:9: running "/Users/abhinavgarg/go/bin/mockgen": fork/exec /Users/abhinavgarg/go/bin/mockgen: no such file or directory
```
Tested by removing the binary and re-running `make generate` after these changes.
=> Add mockgen dependency to wag-generate-deps

make/node.mk
* Adds a `node-coffee-edit-check` target to node.mk that errors out the build if there are any changes made to coffeescript files.
* Adds a guarded linter block that makes it easier to add lints with problem counts (useful since it makes it easier to decaffeinate if you don't have to fix all lint errors).
=> node.mk: Add coffee checker and guarded linter.

make/node.mk
The previous version only supported stylelint, now it supports eslint and tslint.
=> node.mk: Fix node-guarded-lint.

javascript/.eslintrc.yml, javascript/.node-dev.json, javascript/tsconfig.json, javascript/tslint.json
We want to have a fixed place which contains canonical versions of all the configs needed for node projects. Right now we point to different repos, which means that documentation gets out of date once those repos don't have the latest version.
This PR uses OAuth as the source for `.eslintrc.yml`, `tsconfig.json`, and `tslint.json`. It grabs the `.node-dev.json` from https://clever.atlassian.net/wiki/display/ENG/ES6+at+Clever
=> Update latest configurations for node projects

make/golang.mk
Make it so we can have a greater minor version installed than what is mandated, but the major version must be equal.
=> make: Set up Golang version check to use ^.

make/golang.mk
This helps simplify what users write in their makefile. It also improves build speed locally.
By adding this to their `Makefile`:
```
build:
$(call golang-build,$(PKG),$(EXECUTABLE))
```
it handles doing the right build for local (regular `go build`) vs remote (`go build ` with CGO, ready for Alpine linux).
A big reason to do this is for faster iteration locally. Anecdotally, I see builds that take a few seconds (~1-3 seconds) without CGO taking 10x as long (~10-20 seconds) with CGO.
https://github.com/Clever/dapple/compare/update-makefile
=> make/golang.mk: Add golang-build command

make/golang.mk
running 1.10beta1:
```
$ go version | cut -d" " -f3 | cut -c3- | cut -d. -f2 | sed -E 's/beta[0-9]+//'
10
```
=> allow beta versions

make/golang.mk
- bump dep from v0.3.2 => v0.4.1 0c6ac9e
- golang.mk: cache downloaded `dep` binary in /tmp/  abe9da9
You've already got `dep-v<x>` installed in another project... why
download it again?
From local testing, copying cached version of dep reduces the time to
run `make bin/dep` from ~10s to ~2s
=> Golang mk update dep

make/golang.mk
Adds a check for self references to `golang-dep-vendor-deps`.
This target exists in all our Golang repos' Makefiles, as a dependency of the `install_deps` target. 
Thus, it will cause a failure if there's a self reference in `Gopkg.toml` or `Gopkg.lock` whenever someone runs `make install_deps`, either locally or in CI.
=> golang.mk: check for self-references

make/wag.mk
We recently started running `make generate` as a dependency of `make build`. `make generate` for wag repos installs `jsdoc2md` to generate docs. CI doesn't like how it uses `npm install -g`: https://circleci.com/gh/Clever/pod-racer/4
This changes it to a regular `npm install`
=> install jsdoc2md in relative path

javascript/tslint.json
While setting up Prettier in the Portal, I needed to make these changes to the tslint.json. I specifically added accessibility rules and addressed incompatibilities with Prettier's formatting. Other repos using Prettier (SD2, OAuth, HM) have made similar changes.
=> Update tslint.json to include a11y rules & to be compatible w Prettier

javascript/tslint.json, make/node.mk
Adds the `await-promise` rule to the tslint.json file. Also updates the tslint runner in the Makefile to specify the `--project` flag (without which `await-promise` will not work)
=> Add await promise rule

make/golang.mk
We need the fix for submodules: https://github.com/golang/dep/pull/2168
I'm having issues importing `https://github.com/jaegertracing/jaeger-client-go`
I don't see any breaking changes in the release notes
=> Bump dep version to 0.5.4

make/lambda.mk
Pulling from the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)
> When input files are specified on the command line, tsconfig.json files are ignored.
=> Dont specify file in build cmd

make/README.md, make/sql.mk
[SEC-756](): automate checks for sql injection  
Adds a sql.mk file that enables a `safesql` command that golang repos can add to tests.
Working in [library-analytics-service](https://github.com/Clever/library-analytics-service/pull/9) (check succeeds) and [teacher-authorizations](https://github.com/Clever/teacher-authorizations/pull/99) (check fails).
=> [SEC-756] create sql.mk for golang sql

resources.md
This link 
`http://tech.pro/blog/1402/five-patterns-to-help-you-tame-asynchronous-javascript`
for the five patterns of async js redirects to a shady website. I've replaced it with what I believe is the original article.
I can remove it all together if you think that would be a better idea?
=> Remove shady link

make/sql.mk
[SEC-756](https://clever.atlassian.net/browse/SEC-756) (automate checks for sql injection)  
The previous version of sql.mk (from #132) uses a `PKG` variable that is not defined within sql.mk.  This PR removes the use of `PKG` from sql.mk so that Makefiles can continue to set it up and pass it as an argument to the `run-safesql` command.  
This PR also simplifies the code to install and run safesql, combining both the `go get` step and the actual execution into `run-safesql`.   
Tested by adding this version to [teacher-authorizations](https://circleci.com/gh/Clever/teacher-authorizations/456) (check correctly fails).
=> [SEC-756] remove use of PKG in sql.mk and simplify

make/wag.mk
Folks have been seeing build errors because of issues installing wag. Adding retries to the curls, like https://github.com/Clever/sfncli/pull/88
=> wag.mk - add retries to curls

security/bug-bounty.md
https://clever.atlassian.net/browse/SEC-864
We can now have hackers create a single apps account and use the sandbox district. This means no humans in the loop!
Once this is merged, I'll update in HackerOne (https://hackerone.com/clever/policy)
=> Adds simplified instructions for creating accounts for the bug bounty

make/wag.mk
this PR https://github.com/Clever/wag/pull/303 added a method that uses `async` jsdoc v2 does cannot parse async funcs. This PR bumps the version to 4.
=> update jsdoc-to-markdown version

javascript/.prettierrc.json, javascript/README.md
https://clever.atlassian.net/browse/node-37
Now that Clever has a [shared config for prettier](https://github.com/Clever/prettier-config), let's reference that here and update the formatting documentation. I updated the `format` make target to only format updated files, and I ported over the `format-all` and format-check` commands to be consistent with most of our repos.
The documentation related to linting also needs updating, but I decided not to tackle that in this change.
=> Update JS formatting documentation

make/wag.mk
[Link to JIRA](url)
checks if the `go.mod` file is present. If so executes wag with the ` -output-path` flag. If not, executes wag with the `-go-package` flag
tested command locally
testing on CI https://app.circleci.com/jobs/github/Clever/content-mapping-service/358
=> wag.mk to pass correct flags to wag when using modules

make/lambda.mk
https://clever.atlassian.net/browse/INFRANG-4358
the provided.al2 runtime in lambda is the only runtime that supports
Go and lambda layers.
This runtime assumes that the executable is named `bootstrap`:
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html
This PR changes our lambda build process to include the binary with
the name `bootstrap`. It preserves the old behavior for
backwards-compatability while catapult changes to deploy things with
the new runtime.
I tested this by manually uploading a zip file (for `ingest` in `clever-dev`) and successfully launching and running it with the provided.al2 runtime.
- Microplane this, verify everything deploys ok with the large zip file
- Change catapult to use provided.al2 for Go lambdas
- Change lambda.mk to remove the unused …
=> lambda.mk: migrate to provided.al2 runtime

make/lambda.mk
https://github.com/Clever/frontend-to-end-tester/commit/d5a695538bb1f11b876b0b69e5b6beffb0324b4b
We only have one node lambda so far, but this seems like something we'd want to do in all of them in the future. We could put it in the main Makefile instead of here, but this seems preferable
In theory all of the lambda.mk's should be updated, but in particular I'll just update frontend-to-end-tester
=> lambda.mk include kvconfig in node lambdas

security/bug-bounty.md
[SECNG-499](https://clever.atlassian.net/browse/SECNG-499)
Update security policy regarding rate limit based reports. Specifically, it adds call out to say rate limiting without prior notice to us could promp us to disallow the report from bounty and even ban from the program. See ticket for specific instances where this happened.
👁️ 
Once approved, update the H1 policy!
=> Update security policy re rate limiting

make/golang-v1.mk
https://clever.atlassian.net/browse/INFRANG-4534
In Go 1.16, we shouldn't use `go get` to install tools any more, we should use `go install` since `go get` can make changes to `go.mod` and `go.sum` and we don't want that. (In previous versions of Go, `go install` was available but always installed `latest`. The ability to pin versions is new).
In addition, there's a minor tweak to use the env var `GOFLAGS` which is understood natively by `go`
tools, rather than the ad-hoc `GO_BUILD_FLAGS` mechanism. This has the advantage of automatically
propogating to any commands that use `go` in the main `Makefile` that includes this. The end-user
can still override flags by passing explicit flags (e.g. the `go install -mod=readonly` commands in
this very file will override the `-mod=vendor`.
The two …
=> Prepare golang.mk for Go 1.16

make/sql.mk
This is the same kind of change made to `golang.mk`'s installation of `golint` and `fgt` - we want to install these and not have them interact with the `go.mod` file.
=> Change sql.mk library to work with Go 1.16

make/wag.mk
https://clever.atlassian.net/browse/INFRANG-4688
We shouldn't do this in CI since it means whatever is in Github is not necessarily what is running in prod. 
It also helps when testing out pre-release versions of wag
=> wag.mk: don't download wag or generate code in CI

make/lambda.mk
https://clever.atlassian.net/browse/INFRANG-4796
This PR edits the lambda makefile to compile go lambdas to run on the arm architecture, to allow the lambdas to run on AWS Graviton. All go lambdas _should_ be able to run on arm. 
I only plan to merge this after I have tested with a few lambdas in prod.
=> Have go lambdas compile to arm

make/wag.mk
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-4933)
Broke out the lines to download wag into multiple lines that can each fail and show an error. 
Switched to wget since we are now downloading a temp file and it provides more verbose error messages anyway.
Also changed the verbiage of "Using wag version ..." to indicate the current installed version and then mention what version we are updating to. As saying that we are using a version that we have yet to install is misleading. 
Tested on/off the VPN as well as manually telling it that the latest version is a version that doesn't exist. Got appropriate errors and a halt in execution each time.
=> Infrang 4933 wag mk swallows errors downloading wag

make/wag.mk
[Link to JIRA
](https://clever.atlassian.net/browse/INFRANG-5162)
Changes to allow new output path setup for wagv9. 
Should now also pull in wag v9. 
Bumped two minor versions because the wagv9 beta used a custom wag.mk 0.6.2 that pulled in beta releases.
=> Infrang 5162

make/golang-v1.mk
https://github.com/golang/lint has been deprecated and frozen for 2 years now. We have a 122 repos that are currently using `golang-test-all`.
If we want to add coverage for all of them then we will have to fix linting issues for all of them for a linter that has been now deprecated! Lets stop failing on linting issues to make moving to coverage easy.
In the polymer project infra plans on moving to https://github.com/golangci/golangci-lint which is designed with CI in mind.
=> don't fail on golang linting errors

make/golang-v1.mk
https://clever.atlassian.net/browse/INFRANG-5564
As `golang-setup-coverage` doesn't take any arguments, doing it this way is much cleaner for both this file and the app's Makefile.
Tested with catapult locally
Also update template repos
=> golang-setup-coverage doesn't take any arguments so just define it as a target

security/bug-bounty.md
[SECNG-1988](https://clever.atlassian.net/browse/SECNG-1988)
Update the language to explicitly provide safe harbor for security research and criteria for publishing the vulnerability.
No specific testing since this a documentation update.
💯 once approved
[SECNG-1988]: https://clever.atlassian.net/browse/SECNG-1988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add language to explicit safe harbor and how to publish

make/golang-v1.mk
[https://clever.atlassian.net/browse/INFRANG-6623](https://clever.atlassian.net/browse/INFRANG-6623)
Adds specific builds for CGO and a debuggable build
<details>
Used the following configurations to test normal and debug builds with a service and ark start:
debug:
```bash
build:
$(call golang-debug-build,$(PKG),$(EXECUTABLE))
run: build
KAYVEE_LOG_LEVEL=info dlv --headless --listen :2345 exec --api-version=2 --check-go-version=false --only-same-user=false bin/$(EXECUTABLE)
```
normal build:
```bash
build:
$(call golang-build,$(PKG),$(EXECUTABLE))
run: build
KAYVEE_LOG_LEVEL=info bin/$(EXECUTABLE)
```
</details>
Will also need to update golang.mk across any repo using it with microplane, and update Makefiles to use the new debug and CGO options, as well as the VSCode documentation for …
=> fix(INFRANG-6623): Remove CGO from normal build, add debug build, add CGO-specific build

make/golang-v1.mk, security/bug-bounty.md
[https://clever.atlassian.net/browse/SECNG-3104)](https://clever.atlassian.net/browse/SECNG-3104)
Fixing typos in bug bounty program and golang.mk
<details>
Reviewed typos
</details>
=> fix(SECNG-3104): fix typos in bug bounty and golang.mk

make/golang-v1.mk
[[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-6623)](https://clever.atlassian.net/browse/INFRANG-6623)
After the initial update, several builds are failing with messages similar to the following:
```
can't load package: package github.com/GeertJohan/fgt@262f7b11eec07dc7b147c44641236f3212fee89d: can only use path@version syntax with 'go get'
golang.mk:42: recipe for target '/go/bin/fgt' failed
make: *** [/go/bin/fgt] Error 1
```
This PR changes `go install` to `go get` to add back in support for installing specific versions of external packages we rely on.
<details>
Ran `go get` commands to make sure we could install
</details>
=> fix(INFRANG-6623): Transition go install syntax to go get

make/golang-v1.mk
Reverts Clever/dev-handbook#170
<details>revert</details>
=> Revert "fix(INFRANG-6623): Transition go install syntax to go get"
