Clever/dev-handbook

- git-workflow.md
Why: forgot to force push after rebase and ran into git issues
What: updated instructions
> updated guide with force push

- git-workflow.md
https://clever.atlassian.net/wiki/display/POST/FLARE-53+Postmortem?focusedTaskId=7
> Add best practices around whitespace changes.

- README.md
- golang/README.md
- golang/glide.md
The go-guild should ultimately be responsible for the content of this, but in the meantime, we need a place for golang docs.
> Add some initial docs for gloang

- golang/README.md
- golang/godep.md
Example links will work after https://github.com/Clever/shorty/pull/10 is merged
> add notes on Godep

- make/README.md
- make/golang.mk
- make/thrift.mk
This introduces the master copies of the makefile libraries that have been in review on appasaurus.
> add README & makefile lbraries

- make/golang.mk
Add versioning to `golang.mk`.
> add version to golang.mk

- make/README.md
- make/swagger.mk
cc @rgarcia FYI, adding swagger makefile here
> make: swagger.mk

- make/swagger.mk
@kvigen newest swagger.mk that uses wag and our fork of swagger-codegen
Currently the docker image approach to wag fails with `2016/08/11 22:36:55 Failed to copy hardcoded/middleware.go: open hardcoded/middleware.go: no such file or directory` ... I might fix that before merging this
> update swagger.mk to use wag / swagger-codegen

- make/swagger.mk
for more auto-generated fun, e.g. https://github.com/Clever/wag/pull/18
> run `go generate` on autogenerated swagger files

- golang/glide.md
> glide: add remove dependency directions

- make/golang.mk
ticket: https://clever.atlassian.net/browse/SYNC-114
- Remove the `godep` directives.
- Add `dep` installation with a locked version
- Add vendor target
To be invoked like:
```make
install_deps: golang-dep-vendor-deps
$(call golang-dep-vendor,$(PKG))
```
> update golang.mk to use dep

- golang/README.md
- golang/dep.md
- golang/godep.md
**ticket**: https://clever.atlassian.net/browse/SYNC-114
> add dep guide

- make/golang.mk
see https://clever.atlassian.net/wiki/spaces/ENG/pages/217481220/2017-12-15+Meeting+notes
> make dep ensure verbose, -vendor-only in CircleCI

- make/golang.mk
Context: https://github.com/golang/lint/issues/397
> golang.mk: update golint import path

- make/golang.mk
They fixed it :D 
https://github.com/golang/lint/issues/397#issuecomment-384001884
> Revert golint change

- make/golang.mk
This commit breaks us.... https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58
> import golint from golang.org

- make/wag.mk
see template-wag change: https://github.com/Clever/template-wag/pull/44
> wag.mk: leave mockgen install + mock generation up to users

- git-workflow.md
Fix a typo and the broken link to an atlassian git tutorial
> Update dev handbook readme

- make/lambda.mk
Got this working over a series of PRs in https://github.com/Clever/frontend-to-end-tester, our first Node lambda :tada:
> Add `lambda-build-node` command to lambda.mk

- security/bug-bounty.md
The bug bounty policy has been updated in HackerOne, and is no longer in line with this revision. This adds the changes for the policy.
> Bring bug-bounty document to parity with HackerOne

- security/bug-bounty.md
JIRA: [SEC-809](https://clever.atlassian.net/browse/SEC-809)
To make it clear to bug bounty researchers, reword certain sections to make the onboarding process less of a hassle.
> SEC-809 | Review bug bounty language

- golang/README.md
Dep is (mostly) dead to us.
Or even if not, we should document tools we use here.
> Long live gomod

- security/bug-bounty.md
[SECNG-499](https://clever.atlassian.net/browse/SECNG-499)
Update the .MD formatting a bit
Looks better in H1 with this format.
> minor formatting update

- golang/README.md
- golang/dep.md
- golang/glide.md
- golang/godep.md
- make/wag.mk
[INFRANG-4612](https://clever.atlassian.net/browse/INFRANG-4612)
Fixed a few issues with golang docs.
Minor changes to wag.mk to make it compatible with incremental Makefile.
> INFRANG-4612 update golang docs and wag.mk

- make/wag.mk
same as https://github.com/Clever/catapult/pull/1546
I saw we were seeing a deprecated warning so stop that.
> fix pyyaml so that it doesn't give deprecated soon warning

- security/bug-bounty.md
N/A
update to clarify email content vulnerabilities
> update for email injection

- security/bug-bounty.md
clarification on TLS configuration
> adding TLS configuration

- security/bug-bounty.md
#flare-1256
Call out using LaunchDarkly and Segment API keys will get you disqualified from program.
> Call out Segment w.r.t. #flare-1256

- make/golang-v1.mk
passion
Tested this with some apps locally. Had to make a small change to their Makefile too
To use this Makefile needs to be updated as follows
```
test: $(call golang-setup-coverage) $(PKGS) staticcheck
$(PKGS): gen-go go-generate golang-lint-deps-strict
$(call golang-test-all-strict-cover,$@)
```
We should also add coverage.txt to `.gitignore`.
Users can now run `go tool cover -func=coverage.txt` or `go tool cover -html=coverage.txt`. This also allows us to eventually integrate with something like [codecov](https://about.codecov.io/). https://github.com/codecov/example-go.
> add target to create and store test coverage

- security/bug-bounty.md
[SECNG-2149](https://clever.atlassian.net/browse/SECNG-2149)
add 2 missing 'or' statements - minor clarification
Team review of language and poll for other changes
just merge, copy to H1 program description, and remove from Confluence.
[SECNG-2149]: https://clever.atlassian.net/browse/SECNG-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> small tweaks to clarify language

- make/golang-v1.mk
[https://clever.atlassian.net/browse/INFRANG-6623](https://clever.atlassian.net/browse/INFRANG-6623)
There was a typo on one of the echo statements. Removed the extra "@"
<details>Imported the golang.mk file into another project and verified that I could build</details>
> fix(INFRANG-6623): Removing typo
